a = int(input("Введите свой возраст: "))
b = int(input("Введите текущий год: "))
c = float(input("Введите число Пи: "))
d = str(input("Введите Ваше имея: "))

print(a)
print(b)
print(c)
print(d)
print(a+b+c)